spring:
    config:
        activate:
            on-profile: local

    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password:

    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                show_sql: true
