version: '3'
services:
    mysql:
        image: mysql:latest
        container_name: my-mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
